AmalakAdmin/Controllers/UmsController.cs
using Amlakapp.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AmalakAdmin.Controllers
{
    [Authorize]
    public class UmsController : Controller
    {
        // GET: Ums
        public ActionResult Index()
        {
            db_amlakEntities db = new db_amlakEntities();

            return View(db.Users.ToList());
        }
        
         public ActionResult Delete(string id)
        {
            db_amlakEntities db = new db_amlakEntities();
            User obj = db.Users.Where(x => x.UserID == id).FirstOrDefault();
            if (obj != null)
            {
                db.Users.Remove(obj);
                db.SaveChanges();
                TempData["success"] = "You have successfully deleted account: "+obj.Email;
            }
            else
            {
                TempData["Failed"] = "An error occured,Please try again.";
            }
            
            return RedirectToAction("Index");
        }
        public ActionResult edit(string id)
        {
            db_amlakEntities db = new db_amlakEntities();
            User obj=db.Users.Where(x => x.UserID == id).FirstOrDefault();
            return View(obj);
        }
        [HttpPost]
        public ActionResult edit(User objUser)
        {
            db_amlakEntities db = new db_amlakEntities();
            User obj = db.Users.Where(x => x.UserID == objUser.UserID).FirstOrDefault();
            if (obj!=null){

                obj.BusinessName = objUser.BusinessName;
                obj.Country = objUser.Country;
                obj.City = objUser.City;
                obj.Town = objUser.Town;
                obj.PostCode = objUser.PostCode;
                obj.Building = objUser.Building;
                obj.TelePhone1 = objUser.TelePhone1;
                obj.TelePhone2 = objUser.TelePhone2;
                obj.ShopNo = objUser.ShopNo;
                obj.FirstName = objUser.FirstName;
                obj.LastName = objUser.LastName;
                obj.UserType = objUser.UserType;
                db.Entry(obj).State = EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "You have successfully updated";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

    }
}

AmalakAdmin/Views/Ums/Index.cshtml
@using Amlakapp.Entities
@model IEnumerable <User>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">User Management</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">User Management</li>
    </ol>
    <div class="card mb-4">
        @{
            if (TempData["Success"] != null)
            {
                <text>
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        @TempData["Success"]
                    </div>
                </text>
                TempData["Success"] = null;
            }
            if (TempData["Failed"] != null)
            {
                <text><div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        @TempData["Failed"]
                    </div>
                </text>
                TempData["Failed"] = null;
            }
        }

    </div>
    <div class="card mb-4">
        <div class="card-header"><i class="fas fa-table mr-1"></i>users records</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Email</th>
                            <th>Full Name</th>
                            <th>Status</th>
                            @*<th>User Type</th>*@
                            <th>Added Date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                   
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.Email</td>
                            <td>@item.FirstName  @item.LastName</td>
                            <td>@item.Status</td>
                            @*<td>
                            @{
                                string type = "";
                                if (item.UserType == 50)
                                {
                                    type="Customer";
                                } if (item.UserType == 99)
                                {
                                 type="Admin";
                                } }
                                @type
                            </td>*@
                            <td>@item.AddedDate</td>
                            <td> <a href="/Ums/edit?id=@item.UserID">Edit </a>|
                                 <a href="/Ums/Delete?id=@item.UserID">Delete </a></td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

AmalakAdmin/Views/Ums/edit.cshtml
@using Amlakapp.Entities
@model User
@{
    /**/

    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Update Account";
}

<br />
<br />

@using (Html.BeginForm("edit", "Ums", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.HiddenFor(x => x.UserID)
    <div class="container">
        <div class="card mb-4">

            <div class="card-body">
                <div class="py-5 text-center">
                    <img class="d-block mx-auto mb-4" src="~/assets/images/register_i.png" alt="" width="72" height="72">
                    <h2>Account update form</h2>
                    <p class="lead">Please enter below all information related to business.</p>
                </div>

                <div class="row">

                    <div class="col-md-12 order-md-1">
                        <h4 class="mb-3">Business information</h4>
                        <form class="needs-validation" novalidate>

                            <label> Email:</label>  @Html.DisplayFor(m => m.Email, new { @class = "form-control" })


                            <hr class="mb-4">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label for="firstName">Business Name</label>
                                    @Html.TextBoxFor(m => m.BusinessName, new { @class = "form-control", placeholder = "Enter business name" })
                                    @*<div class="invalid-feedback">
                    Valid first name is required.
                </div>*@
                                </div>
                                <div class="col-md-3 mb-3">
                                    <label for="lastName">First name</label>
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", placeholder = "Enter first name" })

                                </div>
                                <div class="col-md-3 mb-3">
                                    <label for="lastName">Last name</label>
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", placeholder = "Enter last name" })

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label for="cc-name">Telephone 1</label>
                                    @Html.TextBoxFor(m => m.TelePhone1, new { @class = "form-control", placeholder = "Enter telephone" })
                                    <div class="invalid-feedback">

                                    </div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="cc-number">TelePhon 2</label>
                                    @Html.TextBoxFor(m => m.TelePhone2, new { @class = "form-control", placeholder = "Enter telephone 2" })
                                    <div class="invalid-feedback">

                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3 mb-3">
                                    <label for="country">Building</label>
                                    @Html.TextBoxFor(m => m.Building, new { @class = "form-control", placeholder = "Enter Building" })
                                    <div class="invalid-feedback">
                                        Please select a valid country.
                                    </div>
                                </div>
                                <div class="col-md-3 mb-3">
                                    <label for="state">Flat/Office/Shop</label>
                                    @Html.TextBoxFor(m => m.ShopNo, new { @class = "form-control", placeholder = "Enter Flat/Office/Shop" })

                                </div>
                                <div class="col-md-3 mb-3">
                                    <label for="zip">Street</label>
                                    @Html.TextBoxFor(m => m.Street, new { @class = "form-control", placeholder = "Enter Street" })
                                </div>
                                <div class="col-md-3 mb-3">
                                    <label for="zip">Town</label>
                                    @Html.TextBoxFor(m => m.Town, new { @class = "form-control", placeholder = "Enter Town" })
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-5 mb-3">
                                    <label for="country">Country</label>

                                    @Html.DropDownListFor(m => m.Country, new List<SelectListItem> {
                                   new SelectListItem { Text = "United State", Value = "United State" },
                                   new SelectListItem { Text = "Canada", Value = "Canada" },
                                       new SelectListItem { Text = "Pakistan", Value = "Pakistan" }

                               }, "Select Gender", new { @class = "custom-select d-block w-100" })


                                </div>
                                <div class="col-md-4 mb-3">
                                    <label for="state">State</label>
                                    @Html.TextBoxFor(m => m.City, new { @class = "form-control", placeholder = "Enter City" })
                                </div>
                                <div class="col-md-3 mb-3">
                                    <label for="zip">Postcode</label>
                                    @Html.TextBoxFor(m => m.PostCode, new { @class = "form-control", placeholder = "Enter Postcode" })
                                    <div class="invalid-feedback">
                                        Postcode code required.
                                    </div>
                                </div>
                            </div>
                            <hr class="mb-4">


                            <button class="btn btn-primary btn-lg btn-block" type="submit">Update</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
}